apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
spec:
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: diablo2050/capestone:${CIRCLE_WORKFLOW_ID:0:7}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
